(define-skeleton template-python-minimal
  "Minimal template for new python file"
  ""
  "#!/usr/bin/env python\n"
  "# -*- coding: utf-8 -*-\n"
  "# ================================= #\n"
  "# Python script                     #\n"
  "# Author: Alexei Panov              #\n"
  "# e-mail: me AT elemc DOT name      #\n"
  "# ================================= #\n"
  "\n\n"
)

(define-skeleton template-python-solo
  "Template for selfexec new python file"
  ""
  "#!/usr/bin/env python\n"
  "# -*- coding: utf-8 -*-\n"
  "# ================================= #\n"
  "# Python script                     #\n"
  "# Author: Alexei Panov              #\n"
  "# e-mail: me AT elemc DOT name      #\n"
  "# ================================= #\n"
  "\n"
  "import sys\n"
  "\n"
  "\n"
  "if __name__ == '__main__':\n"
  "\n"
)

(define-skeleton template-python-class
  "Template for class new python file"
  ""
  "#!/usr/bin/env python\n"
  "# -*- coding: utf-8 -*-\n"
  "# ================================= #\n"
  "# Python script                     #\n"
  "# Author: Alexei Panov              #\n"
  "# e-mail: me AT elemc DOT name      #\n"
  "# ================================= #\n"
  "\n"
  "\n"
  "class SomeClass:\n"
  "\tdef __init__(self):\n"
  "\t\tpass\n"
  "\n"
  "\tdef __del__(self):\n"
  "\t\tpass\n"
)

(define-skeleton template-bash-minimal
  "Template for new minimal bash file"
  ""
  "#!/bin/sh\n"
  "# ================================= #\n"
  "# Shell script                      #\n"
  "# Author: Alexei Panov              #\n"
  "# e-mail: me AT elemc DOT name      #\n"
  "# ================================= #\n"
  "\n"
  "\n"
)
